FROM python:3.7-slim

# surpress terminal error messages
ENV DEBIAN_FRONTEND noninteractive

# update the os
RUN apt-get clean \
    && apt-get -y update

# grab python packages that we need
RUN apt-get -y install python3-dev

# COPY python/PIP requirements over in a text file
COPY requirements.txt /srv/example-app/requirements.txt
# install python libraries
RUN pip install -r /srv/example-app/requirements.txt --src /usr/local/src

#set default directory
WORKDIR /srv/example-app

# copy codebase over
COPY . /srv/example-app/

# set perms
RUN chmod +x start.sh
CMD ["./start.sh"]
